### ISSUE TITLE
Code and assignment solution to the September 2020 batch

### ISSUE THREAD

**Issue by Namanmittal0007** [projjal1/Social-Networks-NPTEL#1]
I would like to add to this repository with all the codes taught and the solution to the assignments for the september 2020 session.

**Comment by projjal1** [comment]
Okay, this I think is a great initiative. I appreciate it. I am adding you as a collaborator for this repository.

**Comment by projjal1** [comment]
One thing you can clone the repo and create a folder "assignment" and submit there.

**Comment by projjal1** [comment]
Yeah, I think this is a great initiative. So one thing you can do, create a folder "assignment" after cloning this repo. Then put your codes there. Submit a PR I will be happy to merge that. Kudos..

**Comment by projjal1** [comment]
If this is for Hacktober Fest 2020, I would advise you to make a PR with at least 2 weeks assn. I will merge PR as soon as possible.

**Comment by Namanmittal0007** [comment]
Thank you, surely I will be making my first  pull request with 2 weeks assignment and will be completing the whole course thereafter.

**Comment by projjal1** [comment]
This course is amazing. Hope you will derive amazing insights from it.
